# Generated by Django 5.0.4 on 2024-04-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_active_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
