# Generated by Django 5.0.4 on 2024-05-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0003_useraddress_remove_user_address_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.ManyToManyField(blank=True, null=True, related_name='addresses', to='app_account.useraddress'),
        ),
    ]
