# Generated by Django 5.0.4 on 2024-06-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0004_alter_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_cart',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
