# Generated by Django 5.0.4 on 2024-07-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0005_user_user_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.ManyToManyField(blank=True, related_name='addresses', to='app_account.useraddress'),
        ),
    ]
