# Generated by Django 5.0.4 on 2024-07-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0005_remove_user_address_delete_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_cart',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
