# Generated by Django 5.0.4 on 2024-07-06 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0006_alter_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
