# Generated by Django 5.0.4 on 2024-07-07 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0008_useraddress_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
