# Generated by Django 5.0.4 on 2024-05-17 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_post_views_view'),
    ]

    operations = [
        migrations.DeleteModel(
            name='View',
        ),
    ]
