# Generated by Django 5.0.4 on 2024-05-21 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='body',
        ),
    ]
