# Generated by Django 5.0.4 on 2024-07-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
