# Generated by Django 5.0.4 on 2024-07-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payment', '0002_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='main_address',
            field=models.BooleanField(default=True),
        ),
    ]
